### ISSUE TITLE
[BUG] Remote exceptions not propogated with backtrace

### ISSUE THREAD

**Issue by robertu94** [deephyper/deephyper#152]
Thanks again for your work on Deephyper!

**Describe the bug**
When a worker process throws an exception using the MPIExector, while the text and type of the exception is propogated, the context and backtrace surrounding it is lost.

**To Reproduce**

```python
import pathlib
import os
import logging
import mpi4py
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
mpi4py.rc.initialize = False
mpi4py.rc.threads = True
mpi4py.rc.thread_level = "multiple"
import tensorflow as tf
from deephyper.evaluator import Evaluator
from deephyper.search.hps import CBO
from deephyper.problem import HpProblem
from mpi4py import MPI


if not MPI.Is_initialized():
    MPI.Init_thread()

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()
gpu_per_node = 1
gpu_local_idx = rank % gpu_per_node
node = int(rank / gpu_per_node)

gpus = tf.config.list_physical_devices("GPU")
if gpus:
    # Restrict TensorFlow to only use the first GPU
    try:
        tf.config.set_visible_devices(gpus[gpu_local_idx], "GPU")
        tf.config.experimental.set_memory_growth(gpus[gpu_local_idx], True)
        logical_gpus = tf.config.list_logical_devices("GPU")
        logging.info(f"[r={rank}]: {len(gpus)} Physical GPUs, {len(logical_gpus)} Logical GPU")
    except RuntimeError as e:
        # Visible devices must be set before GPUs have been initialized
        logging.info(f"{e}")



hp_problem = HpProblem()
hp_problem.add_hyperparameter((-10.0, 10.0), "x")


def inner(config):
    raise RuntimeError("oops")
    return - config["x"]**2


def run(config):
    return inner(config)


timeout = 10
search_log_dir = "search_log/"
pathlib.Path(search_log_dir).mkdir(parents=False, exist_ok=True)

if rank == 0:
    # Evaluator creation
    print("Creation of the Evaluator...")

with Evaluator.create(
    run,
    method="mpicomm",
) as evaluator:
    if evaluator is not None:
        print(f"Creation of the Evaluator done with {evaluator.num_workers} worker(s)")

        # Search creation
        print("Creation of the search instance...")
        search = CBO(
            hp_problem,
            evaluator,
        )
        print("Creation of the search done")

        # Search execution
        print("Starting the search...")
        results = search.search(timeout=timeout)
        print("Search is done")

        results.to_csv(os.path.join(search_log_dir, "results.csv"))

```

**Expected behavior**

I would expect to see a traceback for the worker's exception which includes `inner` and `run` functions in the traceback

**Screenshots**

```
(deephyper38) [runderwood@defiant dh-bugs-exception]$ mpiexec -np 6 python example.py 
Creation of the Evaluator...
Creation of the Evaluator done with 5 worker(s)
Creation of the search instance...
Creation of the search done
Starting the search...
Traceback (most recent call last):
  File "example.py", line 75, in <module>
    results = search.search(timeout=timeout)
  File "/home/runderwood/.conda/envs/deephyper38/lib/python3.8/site-packages/deephyper/search/_search.py", line 131, in search
    self._search(max_evals, timeout)
  File "/home/runderwood/.conda/envs/deephyper38/lib/python3.8/site-packages/deephyper/search/hps/_cbo.py", line 221, in _search
    new_results = self._evaluator.gather(self._gather_type, size=1)
  File "/home/runderwood/.conda/envs/deephyper38/lib/python3.8/site-packages/deephyper/evaluator/_evaluator.py", line 264, in gather
    job = task.result()
  File "/home/runderwood/.conda/envs/deephyper38/lib/python3.8/site-packages/deephyper/evaluator/_evaluator.py", line 205, in _execute
    job = await self.execute(job)
  File "/home/runderwood/.conda/envs/deephyper38/lib/python3.8/site-packages/deephyper/evaluator/_mpi_comm.py", line 69, in execute
    sol = await self.loop.run_in_executor(self.master_executor, run_function)
RuntimeError: oops
```

**Desktop (please complete the following information):**
 - OS: Fedora 36, Ubuntu 18.04
 - System: Laptop/ThetaGPU
 - Python version Python 3.8 (from Anaconda)
 - DeepHyper Version 0.4.0, 0.4.2

**Additional context**

Our team develops extensions to deephyper that run in the worker processes; not having detailed exceptions makes it harder for us to determine when some breaks (often our fault) what happened.

**Comment by Deathn0t** [comment]
I reproduced the situation and propose the following solution. Let me know if this is good for you.

```console
Creation of the Evaluator...
Creation of the Evaluator done with 1 worker(s)
Creation of the search instance...
Creation of the search done
Starting the search...
Traceback (most recent call last):
  File "/Users/romainegele/Documents/Argonne/deephyper/deephyper/evaluator/_mpi_comm.py", line 24, in catch_exception
    result = run_func()
  File "/Users/romainegele/Desktop/test/test.py", line 50, in run
    return inner(config)
  File "/Users/romainegele/Desktop/test/test.py", line 45, in inner
    raise RuntimeError("oops")
RuntimeError: oops

Exception happening in remote rank was propagated to root process.

Traceback (most recent call last):
  File "/Users/romainegele/Documents/Argonne/deephyper/deephyper/evaluator/_mpi_comm.py", line 24, in catch_exception
    result = run_func()
  File "/Users/romainegele/Desktop/test/test.py", line 50, in run
    return inner(config)
  File "/Users/romainegele/Desktop/test/test.py", line 45, in inner
    raise RuntimeError("oops")
RuntimeError: oops

Exception happening in remote rank was propagated to root process.

Traceback (most recent call last):
  File "/Users/romainegele/Documents/Argonne/deephyper/deephyper/evaluator/_mpi_comm.py", line 24, in catch_exception
    result = run_func()
  File "/Users/romainegele/Desktop/test/test.py", line 50, in run
    return inner(config)
  File "/Users/romainegele/Desktop/test/test.py", line 45, in inner
    raise RuntimeError("oops")
RuntimeError: oops

Exception happening in remote rank was propagated to root process.

Traceback (most recent call last):
  File "/Users/romainegele/Desktop/test/test.py", line 78, in <module>
    results = search.search(timeout=timeout)
  File "/Users/romainegele/Documents/Argonne/deephyper/deephyper/search/_search.py", line 131, in search
    self._search(max_evals, timeout)
  File "/Users/romainegele/Documents/Argonne/deephyper/deephyper/search/hps/_cbo.py", line 252, in _search
    new_results = self._evaluator.gather(self._gather_type, size=1)
  File "/Users/romainegele/Documents/Argonne/deephyper/deephyper/evaluator/_evaluator.py", line 266, in gather
    job = task.result()
  File "/Users/romainegele/Documents/Argonne/deephyper/deephyper/evaluator/_evaluator.py", line 207, in _execute
    job = await self.execute(job)
  File "/Users/romainegele/Documents/Argonne/deephyper/deephyper/evaluator/_mpi_comm.py", line 92, in execute
    raise RunFunctionError
deephyper.core.exceptions.RunFunctionError
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[3842,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by Deathn0t** [comment]
pushed to `develop` branch after this commit: https://github.com/deephyper/deephyper/commit/034a066b4cce34fb0cb3eca648d3367881f475bf
