### ISSUE TITLE
[BUG] Tutorial number 5  Basic NAS

### ISSUE THREAD

**Issue by bbanzai88** [deephyper/deephyper#172]
When I run the colab tutorial (tutorial_05.ipynb) and run the command:

results = search.search(10)

I get the error below.. Any ideas on what I can do? Thank you!

(pid=12493) 2023-03-06 19:37:08.478592: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
(pid=12493) 2023-03-06 19:37:08.478780: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
(pid=12493) 2023-03-06 19:37:08.478804: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
(pid=12494) 2023-03-06 19:37:08.978691: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
(pid=12494) 2023-03-06 19:37:08.978859: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
(pid=12494) 2023-03-06 19:37:08.978898: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
(run_base_trainer pid=12493) 2023-03-06 19:37:15.391539: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
(run_base_trainer pid=12494) 2023-03-06 19:37:15.536558: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
---------------------------------------------------------------------------
RayTaskError(ValueError)                  Traceback (most recent call last)
[<ipython-input-8-88e8c065bfb9>](https://localhost:8080/#) in <module>
----> 1 results = search.search(10)

9 frames
[/usr/lib/python3.8/asyncio/futures.py](https://localhost:8080/#) in result(self)
    176         self.__log_traceback = False
    177         if self._exception is not None:
--> 178             raise self._exception
    179         return self._result
    180 

RayTaskError(ValueError): ray::run_base_trainer() (pid=12493, ip=172.28.0.12)
  File "/usr/local/lib/python3.8/dist-packages/deephyper/nas/run/_run_base_trainer.py", line 119, in run_base_trainer
    history = trainer.train(with_pred=with_pred, last_only=last_only)
  File "/usr/local/lib/python3.8/dist-packages/deephyper/nas/trainer/_base.py", line 517, in train
    history = self.model.fit(
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_file0sexto81.py", line 15, in tf__train_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1233, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1222, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1027, in train_step
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 527, in minimize
        self.apply_gradients(grads_and_vars)
    File "/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1140, in apply_gradients
        return super().apply_gradients(grads_and_vars, name=name)
    File "/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 634, in apply_gradients
        iteration = self._internal_apply_gradients(grads_and_vars)
    File "/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1166, in _internal_apply_gradients
        return tf.__internal__.distribute.interim.maybe_merge_call(
    File "/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1216, in _distributed_apply_gradients_fn
        distribution.extended.update(
    File "/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1213, in apply_grad_to_update_var  **
        return self._update_step(grad, var)
    File "/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 224, in _update_step
        self.update_step(gradient, variable)
    File "/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_experimental/adam.py", line 200, in update_step
        variable.assign_sub((m * alpha) / (tf.sqrt(v) + self.epsilon))

    ValueError: None values not supported.

**Comment by Deathn0t** [comment]
Hello @bbanzai88 , thank you for reporting this issue! Apparently this is due to the recent `tensorflow==2.11` update and the `epsilon` parameter of optimisers. For a quick workaround you can update the code of the cell where the `problem` is defined with the following:


```python
# Fixed hyperparameters for all trained models
problem.hyperparameters(
    batch_size=32,
    learning_rate=0.01,
    optimizer="adam",
    epsilon=1e-7,  # To avoid passing "None" to the optimizer
    num_epochs=20,
    callbacks=dict(
        EarlyStopping=dict(
            monitor="val_r2", mode="max", verbose=0, patience=5
        )
    ),
)
```

I will push a fix in the next update of deephyper as well. Let me know if this resolves the issue for you!

**Comment by Deathn0t** [comment]
Fixing the issue in 8cb7fb9b5f1590da4918139367f9c6e3470930b7 (for future release) and in [93328aed4308dcf40fbe7cba5a7264c46d3b15c0](https://github.com/deephyper/tutorials/commit/93328aed4308dcf40fbe7cba5a7264c46d3b15c0)

**Comment by bbanzai88** [comment]
Thank you!!

-th
