### ISSUE TITLE
[BUG] Cannot run network architecture search 

### ISSUE THREAD

**Issue by rohitvuppala** [deephyper/deephyper#180]
**Describe the bug**
Unable to run network architecture search 

**To Reproduce**
[Steps to reproduce the behavior:]Run the file (https://github.com/deephyper/anl-22-summer-workshop/blob/main/notebooks/2-Neural-Architecture-Search.ipynb), fails at block 18

**Expected behavior**
Network architecture search should be successful 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Google Colab, Ubuntu
 - System: Google Colab, Conda env 
 - Python version 3.9 
 - DeepHyper Version 0.4.1,0.4.2,0.5.0

**Additional context**
Version 0.4.2 errors with:
```
/usr/local/lib/python3.9/dist-packages/deephyper/evaluator/_evaluator.py:101: UserWarning: Applying nest-asyncio patch for IPython Shell!
  warnings.warn(
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-17-10be92266985>](https://localhost:8080/#) in <module>
      3 
      4 
----> 5 agebo_search = AgEBO(
      6     problem,
      7     run_base_trainer,

2 frames
[/usr/local/lib/python3.9/dist-packages/deephyper/skopt/learning/forest.py](https://localhost:8080/#) in __init__(self, n_estimators, criterion, max_depth, min_samples_split, min_samples_leaf, min_weight_fraction_leaf, max_features, max_leaf_nodes, min_impurity_decrease, bootstrap, oob_score, n_jobs, random_state, verbose, warm_start, ccp_alpha, max_samples, min_variance, splitter)
    232         splitter="random"
    233     ):
--> 234         super().__init__(
    235             base_estimator=DecisionTreeRegressor(splitter=splitter),
    236             n_estimators=n_estimators,

TypeError: __init__() missing 1 required positional argument: 'estimator'
```
version 0.5.0 errors with:
```
/usr/local/lib/python3.9/dist-packages/deephyper/evaluator/_evaluator.py:126: UserWarning: Applying nest-asyncio patch for IPython Shell!
  warnings.warn(
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-17-10be92266985>](https://localhost:8080/#) in <module>
     10     random_state=42,
     11 )
---> 12 results = agebo_search.search(max_evals=30)

11 frames
[/usr/local/lib/python3.9/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py](https://localhost:8080/#) in tf___update_step_xla(self, gradient, variable, key)
     26                 try:
     27                     do_return = True
---> 28                     retval_ = ag__.converted_call(ag__.ld(self)._update_step, (ag__.ld(gradient), ag__.ld(variable)), None, fscope)
     29                 except:
     30                     do_return = False

ValueError: in user code:

    File "/usr/local/lib/python3.9/dist-packages/keras/engine/training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.9/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 208, in _update_step_xla  *
        return self._update_step(gradient, variable)
    File "/usr/local/lib/python3.9/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 224, in _update_step  **
        self.update_step(gradient, variable)
    File "/usr/local/lib/python3.9/dist-packages/keras/optimizers/optimizer_experimental/adam.py", line 200, in update_step
        variable.assign_sub((m * alpha) / (tf.sqrt(v) + self.epsilon))

    ValueError: None values not supported.
```

I'm not sure what the problem is.

**Comment by Deathn0t** [comment]
Hello, can you test the following workaround fixes your issue: https://github.com/deephyper/deephyper/issues/172

In short adding the `epsilon=1e-7` the the `problem.hyperparameters`.

**Comment by rohitvuppala** [comment]
Thank you!, that seems to fix the issue.
