### ISSUE TITLE
Installation on macOS currently requires OpenSSL workaround

### ISSUE THREAD

**Issue by felker** [deephyper/deephyper#20]
Currently on macOS Catalina, using Anaconda, I have successfully installed `pip install deephyper`. However,

```
python -m deephyper.search.hps.ambs --problem deephyper.benchmark.hps.polynome2.Problem --run deephyper.benchmark.hps.polynome2.run
```
returns:
```
/usr/local/anaconda3/envs/frnn/lib/python3.7/site-packages/scikit_learn-0.21.3-py3.7-macosx-10.9-x86_64.egg/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
 **********************************************************************************
   Maximizing the return value of function: deephyper.benchmark.hps.polynome2.run
 **********************************************************************************
Uncaught exception <class 'ImportError'>: dlopen(/usr/local/anaconda3/envs/frnn/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/lib.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/anaconda3/envs/frnn/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/libarrow.14.dylib
  Reason: image not foundTraceback (most recent call last):
  File "/usr/local/anaconda3/envs/frnn/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/anaconda3/envs/frnn/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/anaconda3/envs/frnn/lib/python3.7/site-packages/deephyper/search/hps/ambs.py", line 112, in <module>
    search = AMBS(**vars(args))
  File "/usr/local/anaconda3/envs/frnn/lib/python3.7/site-packages/deephyper/search/hps/ambs.py", line 48, in __init__
    super().__init__(problem, run, evaluator, **kwargs)
  File "/usr/local/anaconda3/envs/frnn/lib/python3.7/site-packages/deephyper/search/search.py", line 53, in __init__
    self.evaluator = Evaluator.create(self.run_func, method=evaluator, **kwargs)
  File "/usr/local/anaconda3/envs/frnn/lib/python3.7/site-packages/deephyper/evaluator/evaluate.py", line 126, in create
    from deephyper.evaluator.ray_evaluator import RayEvaluator
  File "/usr/local/anaconda3/envs/frnn/lib/python3.7/site-packages/deephyper/evaluator/ray_evaluator.py", line 7, in <module>
    import ray
  File "/usr/local/anaconda3/envs/frnn/lib/python3.7/site-packages/ray/__init__.py", line 28, in <module>
    import pyarrow  # noqa: F401
  File "/usr/local/anaconda3/envs/frnn/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/__init__.py", line 49, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: dlopen(/usr/local/anaconda3/envs/frnn/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/lib.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/anaconda3/envs/frnn/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/libarrow.14.dylib
  Reason: image not found
```

Apple has [had a complicated relationship](https://apple.stackexchange.com/questions/324222/how-official-is-libressl-support-in-high-sierra) with OpenSSL, LibreSSL, and CommonCrypto. I normally install OpenSSL when necessary with `brew install openssl`, but  Homebrew bumped their formula for OpenSSL from 1.0 to 1.1 [on 2019-11-21](https://github.com/Homebrew/homebrew-core/commit/0349a7ca76f483483c6d5c1d4cfe6b458dee2665) and [removed the openssl, openssl@1.0 formulas](https://github.com/Homebrew/homebrew-core/pull/46876) since OpenSSL 1.0 will reach EOL on 2019-12-31. This has broken dependencies for a lot of people, including for the DeepHyper dependency, Ray. 

One workaround is given [here](https://github.com/EOSIO/eos/issues/8235) to downgrade to v1.0:
```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/30fd2b68feb458656c2da2b91e577960b11c42f4/Formula/openssl.rb
```

I also think that bumping 
https://github.com/deephyper/deephyper/blob/149d1c73d38d8061b58d53b94b7db49627a81487/setup.py#L44

to https://github.com/ray-project/ray/releases/tag/ray-0.7.6 fixes the issue. 

This is obviously not an issue with DeepHyper per se, but I figured that other macOS users might be encountering this.

**Comment by Deathn0t** [comment]
Hi @felker, thank you for reporting this. Have you tried just by `pip install ray==0.7.6`? I can update the version in the setup.py if this is enough.

**Comment by felker** [comment]
Yes, that works for me, and I have opened a PR with this change (although I used `>=`, and I realize you may be pinning exact dependency versions in order to avoid issues like this).

In an attempt to understand how the distributed `.whl` depends on OpenSSL, I also briefly tried installing Ray (v0.7.2 and v0.7.6) from source with my OpenSSL library, but this appears to be broken: https://github.com/ray-project/ray/issues/6373

There seems to be no easy way for introspection on the system libraries used to build the Ray `.whl`; and in fact, the reason Ray v0.7.6 works might be because the bundled `pyarrow` v0.14.0 comes from a different wheel (specified in Ray's `build.sh`, changed in https://github.com/ray-project/ray/commit/4e823138917eebacf2a5285fdcf4a217ca78e2aa#diff-0b83f9dedf40d7356e5ca147a077acb4, e.g.) generated by https://github.com/ray-project/arrow-build. There are several recent Issues and PRs in https://github.com/apache/arrow/ related to these OpenSSL considerations, e.g. https://github.com/apache/arrow/pull/5895, https://github.com/apache/arrow/pull/4577, and https://github.com/apache/arrow/pull/482.

In the unzipped Ray wheels, `otool -L purelib/ray/pyarrow_files/pyarrow/libarrow*.dylib`:

**0.7.2**:
```
libarrow.14.dylib:
	@rpath/libarrow.14.dylib (compatibility version 14.0.0, current version 14.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libarrow_boost_system.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libarrow_boost_filesystem.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libarrow_boost_regex.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
```

**0.7.6**:
```
libarrow.100.dylib:
	@rpath/libarrow.100.dylib (compatibility version 100.0.0, current version 100.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libarrow_boost_system.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libarrow_boost_filesystem.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libarrow_boost_regex.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
```
