### ISSUE TITLE
[BUG] multi-objective optimization

### ISSUE THREAD

**Issue by miniskar** [deephyper/deephyper#223]
I am having a small example to do multi-objective optimization for given set of hyper parameters. 
Here is the code:
```
algorithm= [0, 1, 2, 3]
archs=[0, 1, 2, 3, 4]
kernel=[0, 1, 2, 3, 4, 5]
ntiles=[4, 8, 2]
size =[512, 1024, 2048, 4096, 8192, 16384]

import sys
import os
import pdb
import re
import numpy as np
import pandas as pd
from deephyper.evaluator import Evaluator
from deephyper.problem import HpProblem
from deephyper.search.hps import CBO

def dummy_run(config):
    return config["archs"], config["ntiles"]*10

problem = HpProblem()
evaluator = lambda: Evaluator.create(dummy_run, method="serial", #mpicomm, process, ray, serial, thread
                                method_kwargs={"num_workers": 1})
cwd = os.getcwd()
log_path = os.path.join(cwd, "logs")
search = CBO(
    problem,
    evaluator,
    random_state=42,
    surrogate_model="DUMMY",
    log_dir=log_path,
    verbose=1,
    )
problem.add_hyperparameter(algorithm, "algorithm")
problem.add_hyperparameter(archs, "archs")
problem.add_hyperparameter(kernel, "kernel")
problem.add_hyperparameter(ntiles, "ntiles")
problem.add_hyperparameter(size, "size")
res1 = search.search(max_evals=4)
```

When I run this code, I am getting below error. 
```
scratch/nqx/hunter.sep30/deffe/deephyper/deephyper/skopt/optimizer/optimizer.py:748: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_samples = df_samples[~df_samples.duplicated(keep="first")]
Traceback (most recent call last):
  File "/scratch/nqx/hunter.sep30/deffe/example.py", line 42, in <module>
    res1 = search.search(max_evals=4)
  File "/scratch/nqx/hunter.sep30/deffe/deephyper/deephyper/search/_search.py", line 162, in search
    self._search(max_evals, timeout)
  File "/scratch/nqx/hunter.sep30/deffe/deephyper/deephyper/search/hps/_cbo.py", line 401, in _search
    new_X = self._opt.ask(n_points=self._evaluator.num_workers)
  File "/scratch/nqx/hunter.sep30/deffe/deephyper/deephyper/skopt/optimizer/optimizer.py", line 557, in ask
    x = self._ask()
  File "/scratch/nqx/hunter.sep30/deffe/deephyper/deephyper/skopt/optimizer/optimizer.py", line 844, in _ask
    return self._ask_random_points()
  File "/scratch/nqx/hunter.sep30/deffe/deephyper/deephyper/skopt/optimizer/optimizer.py", line 826, in _ask_random_points
    Xsamples = self._filter_duplicated(Xsamples)
  File "/scratch/nqx/hunter.sep30/deffe/deephyper/deephyper/skopt/optimizer/optimizer.py", line 748, in _filter_duplicated
    df_samples = df_samples[~df_samples.duplicated(keep="first")]
  File "/scratch/nqx/hunter.sep30/deffe/def.dh.venv/lib/python3.10/site-packages/pandas/core/frame.py", line 4093, in __getitem__
    return self._getitem_bool_array(key)
  File "/scratch/nqx/hunter.sep30/deffe/def.dh.venv/lib/python3.10/site-packages/pandas/core/frame.py", line 4149, in _getitem_bool_array
    key = check_bool_indexer(self.index, key)
  File "/scratch/nqx/hunter.sep30/deffe/def.dh.venv/lib/python3.10/site-packages/pandas/core/indexing.py", line 2662, in check_bool_indexer
    raise IndexingError(
pandas.errors.IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).
```

I am wondering whether I am calling add_hyperparameter correctly for the hyperparameters?

**Comment by Deathn0t** [comment]
Hello @miniskar ,

In my case I do not manage to reproduce the error on the latest commit from `develop` branch. Maybe the issue was already solved. 

If you want to test the `develop` version of the software try installing with:

```console
pip install "deephyper @ git+https://github.com/deephyper/deephyper@develop"
```

I have the following code working (your example was not exactly correct for example the definition of `evaluator` was wrong.

```python
from deephyper.evaluator import Evaluator
from deephyper.problem import HpProblem
from deephyper.search.hps import CBO

algorithm = [0, 1, 2, 3]
archs = [0, 1, 2, 3, 4]
kernel = [0, 1, 2, 3, 4, 5]
ntiles = [4, 8, 2]
size = [512, 1024, 2048, 4096, 8192, 16384]


def dummy_run(config):
    return config["archs"], config["ntiles"] * 10


problem = HpProblem()
problem.add_hyperparameter(algorithm, "algorithm")
problem.add_hyperparameter(archs, "archs")
problem.add_hyperparameter(kernel, "kernel")
problem.add_hyperparameter(ntiles, "ntiles")
problem.add_hyperparameter(size, "size")

evaluator = Evaluator.create(
    dummy_run,
    method="serial",  # mpicomm, process, ray, serial, thread
    method_kwargs={"num_workers": 1},
)

search = CBO(
    problem,
    evaluator,
    random_state=42,
    surrogate_model="DUMMY",
    log_dir="logs/",
    verbose=1,
)

res1 = search.search(max_evals=10)
```

**Comment by miniskar** [comment]
Thank you. I think the placement of add_hyperparameter is wrong. I have followed your example and it is working good.
