### ISSUE TITLE
Not user friendly exception while giving a none existing path

### ISSUE THREAD

**Issue by Deathn0t** [deephyper/deephyper#32]
Executing:
```
python -m deephyper.search.hps.ambs --problem ../deephyper/deephyper/benchmark/hps/toyCond/problem.py --run ../deephyper/deephyper/benchmark/hps/toyCond/problem.py --evaluator subprocess
```
Stacktrace example
```
Uncaught exception <class 'TypeError'>: the 'package' argument is required to perform a relative import for '../deephyper/deephyper/benchmark/hps/toyCond/problem'Traceback (most recent call last):
  File "/Users/romainegele/opt/anaconda3/envs/dh/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/romainegele/opt/anaconda3/envs/dh/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/romainegele/Documents/Argonne/deephyper/deephyper/search/hps/ambs.py", line 115, in <module>
    search = AMBS(**vars(args))
  File "/Users/romainegele/Documents/Argonne/deephyper/deephyper/search/hps/ambs.py", line 48, in __init__
    super().__init__(problem, run, evaluator, **kwargs)
  File "/Users/romainegele/Documents/Argonne/deephyper/deephyper/search/search.py", line 43, in __init__
    self.problem = util.generic_loader(problem, 'Problem')
  File "/Users/romainegele/Documents/Argonne/deephyper/deephyper/search/util.py", line 159, in generic_loader
    return load_attr_from(target)
  File "/Users/romainegele/Documents/Argonne/deephyper/deephyper/search/util.py", line 123, in load_attr_from
    module = import_module(str_module)
  File "/Users/romainegele/opt/anaconda3/envs/dh/lib/python3.7/importlib/__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '../deephyper/deephyper/benchmark/hps/toyCond/problem'
```

**Comment by Deathn0t** [comment]
resolved in #a33809b
