### ISSUE TITLE
[BUG] Typo in NAS tutorial

### ISSUE THREAD

**Issue by jke513** [deephyper/deephyper#45]
**Describe the bug**
`deephyper nas random --evaluator ray --problem nas_polynome2.problem.Problem` in [https://deephyper.readthedocs.io/en/latest/tutorials/nas.html](url)

I think it should be `deephyper nas random --evaluator ray --problem nas_problems.polynome2.problem.Problem`

**Screenshots**

Run of  `deephyper nas random --evaluator ray --problem nas_polynome2.problem.Problem`
```
(dh-env) [jkoo@blueslogin1 polynome2]$ deephyper nas random --evaluator ray --problem nas_polynome2.problem.Problem
Uncaught exception <class 'deephyper.core.exceptions.loading.GenericLoaderError'>: Traceback (most recent call last):
  File "/gpfs/fs1/home/jkoo/github/deephyper/deephyper/search/util.py", line 164, in generic_loader
    attr = load_attr_from(target)
  File "/gpfs/fs1/home/jkoo/github/deephyper/deephyper/search/util.py", line 124, in load_attr_from
    module = importlib.import_module(str_module)
  File "/home/jkoo/.conda/envs/dh-env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nas_polynome2'

The attribute 'Problem' cannot be importe from 'nas_polynome2.problem.Problem'.Traceback (most recent call last):
  File "/gpfs/fs1/home/jkoo/github/deephyper/deephyper/search/util.py", line 164, in generic_loader
    attr = load_attr_from(target)
  File "/gpfs/fs1/home/jkoo/github/deephyper/deephyper/search/util.py", line 124, in load_attr_from
    module = importlib.import_module(str_module)
  File "/home/jkoo/.conda/envs/dh-env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nas_polynome2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jkoo/.conda/envs/dh-env/bin/deephyper", line 33, in <module>
    sys.exit(load_entry_point('deephyper', 'console_scripts', 'deephyper')())
  File "/gpfs/fs1/home/jkoo/github/deephyper/deephyper/core/cli/cli.py", line 42, in main
    args.func(**vars(args))
  File "/gpfs/fs1/home/jkoo/github/deephyper/deephyper/core/cli/nas.py", line 37, in main
    search_obj = search_cls(**kwargs)
  File "/gpfs/fs1/home/jkoo/github/deephyper/deephyper/search/nas/full_random.py", line 24, in __init__
    super().__init__(problem=problem, run=run, evaluator=evaluator, **kwargs)
  File "/gpfs/fs1/home/jkoo/github/deephyper/deephyper/search/nas/__init__.py", line 23, in __init__
    super().__init__(problem, run=run, evaluator=evaluator, **kwargs)
  File "/gpfs/fs1/home/jkoo/github/deephyper/deephyper/search/search.py", line 52, in __init__
    self.problem = util.generic_loader(problem, "Problem")
  File "/gpfs/fs1/home/jkoo/github/deephyper/deephyper/search/util.py", line 168, in generic_loader
    raise GenericLoaderError(target, attribute, trace_source)
deephyper.core.exceptions.loading.GenericLoaderError: Traceback (most recent call last):
  File "/gpfs/fs1/home/jkoo/github/deephyper/deephyper/search/util.py", line 164, in generic_loader
    attr = load_attr_from(target)
  File "/gpfs/fs1/home/jkoo/github/deephyper/deephyper/search/util.py", line 124, in load_attr_from
    module = importlib.import_module(str_module)
  File "/home/jkoo/.conda/envs/dh-env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nas_polynome2'

The attribute 'Problem' cannot be importe from 'nas_polynome2.problem.Problem'.
```

Run of  `deephyper nas random --evaluator ray --problem nas_problems.polynome2.problem.Problem`
```
deephyper nas random --evaluator ray --problem nas_problems.polynome2.problem.Problem
 *************************************************************************************
   Maximizing the return value of function: deephyper.search.nas.model.run.alpha.run
 *************************************************************************************
2020-09-01 12:42:44,724 INFO resource_spec.py:231 -- Starting Ray with 33.35 GiB memory available for workers and up to 16.69 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-09-01 12:42:47,575 INFO services.py:1193 -- View the Ray dashboard at localhost:8265
This search doesn't have an exiting procedure...
(pid=3581) train_X shape: (8000, 10)
(pid=3581) train_y shape: (8000, 1)
(pid=3581) valid_X shape: (2000, 10)
(pid=3581) valid_y shape: (2000, 1)
(pid=3581) WARNING:tensorflow:From /home/jkoo/.conda/envs/dh-env/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
(pid=3581) Instructions for updating:
(pid=3581) If using Keras pass *_constraint arguments to layers.
(pid=3581) WARNING:tensorflow:From /gpfs/fs1/home/jkoo/github/deephyper/deephyper/search/nas/model/trainer/train_valid.py:28: The name tf.keras.backend.get_session is deprecated. Please use tf.compat.v1.keras.backend.get_session instead.
(pid=3581)
(pid=3581) WARNING:tensorflow:OMP_NUM_THREADS is no longer used by the default Keras config. To configure the number of threads, use tf.config.threading APIs.
(pid=3581) 2020-09-01 12:43:00.710118: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/intel-mkl-2017.3.196-v7uuj6zmthzln35n2hb7i5u5ybncv5ev/compilers_and_libraries_2017.4.196/linux/tbb/lib/intel64_lin/gcc4.7:/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/intel-mkl-2017.3.196-v7uuj6zmthzln35n2hb7i5u5ybncv5ev/compilers_and_libraries_2017.4.196/linux/compiler/lib/intel64_lin:/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/intel-mkl-2017.3.196-v7uuj6zmthzln35n2hb7i5u5ybncv5ev/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64_lin:/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/intel-mkl-2017.3.196-v7uuj6zmthzln35n2hb7i5u5ybncv5ev/lib:/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/intel-mpi-2017.3-dfphq6kavje2olnichisvjjndtridrok/compilers_and_libraries_2017.4.196/linux/mpi/mic/lib:/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/intel-mpi-2017.3-dfphq6kavje2olnichisvjjndtridrok/compilers_and_libraries_2017.4.196/linux/mpi/intel64/lib:/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-17.0.4-74uvhjiulyqgvsmywifbbuo46v5n42xc/tbb/lib/intel64/gcc4.4:/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-17.0.4-74uvhjiulyqgvsmywifbbuo46v5n42xc/lib/intel64:/soft/mpich3/intel-13.1/lib:/soft/mpich3/intel-13.1/lib
(pid=3581) 2020-09-01 12:43:00.710704: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
(pid=3581) 2020-09-01 12:43:00.710786: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (blueslogin1): /proc/driver/nvidia/version does not exist
(pid=3581) 2020-09-01 12:43:00.824195: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2568190000Hz
(pid=3581) 2020-09-01 12:43:00.826721: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x557fe00be950 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
(pid=3581) 2020-09-01 12:43:00.826758: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
(pid=3581) WARNING:tensorflow:Expected a shuffled dataset but input dataset `x` is not shuffled. Please invoke `shuffle()`on input dataset.
(pid=3581) Train on 250 steps, validate on 63 steps
(pid=3581) Epoch 1/20
  1/250 [..............................] - ETA: 2:19 - loss: 16.1466 - r2: -13.2896
 26/250 [==>...........................] - ETA: 5s - loss: 2.7257 - r2: -1.8484
 47/250 [====>.........................] - ETA: 2s - loss: 1.9577 - r2: -1.0532
 70/250 [=======>......................] - ETA: 1s - loss: 1.6224 - r2: -0.6890
 93/250 [==========>...................] - ETA: 1s - loss: 1.4246 - r2: -0.4893
115/250 [============>.................] - ETA: 0s - loss: 1.2935 - r2: -0.3564
140/250 [===============>..............] - ETA: 0s - loss: 1.1997 - r2: -0.2524
166/250 [==================>...........] - ETA: 0s - loss: 1.1169 - r2: -0.1614
190/250 [=====================>........] - ETA: 0s - loss: 1.0597 - r2: -0.1005
218/250 [=========================>....] - ETA: 0s - loss: 0.9931 - r2: -0.0333
249/250 [============================>.] - ETA: 0s - loss: 0.9348 - r2: 0.0317
250/250 [==============================] - 1s 5ms/step - loss: 0.9325 - r2: 0.0336 - val_loss: 0.4275 - val_r2: 0.5657
(pid=3581) Epoch 2/20
  1/250 [..............................] - ETA: 0s - loss: 0.3700 - r2: 0.6726
 28/250 [==>...........................] - ETA: 0s - loss: 0.3953 - r2: 0.5612
 56/250 [=====>........................] - ETA: 0s - loss: 0.3604 - r2: 0.6124
 85/250 [=========>....................] - ETA: 0s - loss: 0.3396 - r2: 0.6378
116/250 [============>.................] - ETA: 0s - loss: 0.3203 - r2: 0.6562
144/250 [================>.............] - ETA: 0s - loss: 0.3007 - r2: 0.6792
```

**Desktop (please complete the following information):**
 - OS: Linux
 - System: LCRC
 - Python version 3.7
 - DeepHyper Version 0.1.11

**Comment by Deathn0t** [comment]
thanks @jke513 resolved in 33457fe928dddf70775ad0e3aaac18e4ad820895
