### ISSUE TITLE
[BUG] deephyper on laptop results in error about numpy.ndarray size

### ISSUE THREAD

**Issue by BethanyL** [deephyper/deephyper#56]
I tried this example from the documentation on my laptop: 
deephyper hps ambs --problem deephyper.benchmark.hps.polynome2.Problem --run deephyper.benchmark.hps.polynome2.run

I got this error: 

Traceback (most recent call last):
  File "/opt/anaconda3/envs/deephyper-Feb21/bin/deephyper", line 33, in <module>
    sys.exit(load_entry_point('deephyper', 'console_scripts', 'deephyper')())
  File "/opt/anaconda3/envs/deephyper-Feb21/bin/deephyper", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/anaconda3/envs/deephyper-Feb21/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 98, in load
    module = import_module(match.group('module'))
  File "/opt/anaconda3/envs/deephyper-Feb21/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/blusch/deephyper/deephyper/core/cli/__init__.py", line 1, in <module>
    from deephyper.core.cli.cli import main
  File "/Users/blusch/deephyper/deephyper/core/cli/cli.py", line 9, in <module>
    from deephyper.core.cli import hps, nas, balsam_submit
  File "/Users/blusch/deephyper/deephyper/core/cli/hps.py", line 6, in <module>
    from deephyper.search.util import load_attr_from
  File "/Users/blusch/deephyper/deephyper/search/__init__.py", line 6, in <module>
    from deephyper.search.search import Search
  File "/Users/blusch/deephyper/deephyper/search/search.py", line 8, in <module>
    from deephyper.evaluator.evaluate import Evaluator
  File "/Users/blusch/deephyper/deephyper/evaluator/__init__.py", line 5, in <module>
    from deephyper.evaluator.evaluate import Encoder
  File "/Users/blusch/deephyper/deephyper/evaluator/evaluate.py", line 14, in <module>
    import skopt
  File "/opt/anaconda3/envs/deephyper-Feb21/lib/python3.7/site-packages/skopt/__init__.py", line 45, in <module>
    from . import callbacks
  File "/opt/anaconda3/envs/deephyper-Feb21/lib/python3.7/site-packages/skopt/callbacks.py", line 17, in <module>
    from skopt.utils import dump
  File "/opt/anaconda3/envs/deephyper-Feb21/lib/python3.7/site-packages/skopt/utils.py", line 19, in <module>
    from .sampler import Sobol, Lhs, Hammersly, Halton, Grid
  File "/opt/anaconda3/envs/deephyper-Feb21/lib/python3.7/site-packages/skopt/sampler/__init__.py", line 4, in <module>
    from .lhs import Lhs
  File "/opt/anaconda3/envs/deephyper-Feb21/lib/python3.7/site-packages/skopt/sampler/lhs.py", line 9, in <module>
    from ..space import Space, Categorical
  File "/opt/anaconda3/envs/deephyper-Feb21/lib/python3.7/site-packages/skopt/space/__init__.py", line 5, in <module>
    from .space import *
  File "/opt/anaconda3/envs/deephyper-Feb21/lib/python3.7/site-packages/skopt/space/space.py", line 27, in <module>
    import ConfigSpace as CS
  File "/opt/anaconda3/envs/deephyper-Feb21/lib/python3.7/site-packages/ConfigSpace/__init__.py", line 37, in <module>
    from ConfigSpace.configuration_space import Configuration, \
  File "ConfigSpace/configuration_space.pyx", line 39, in init ConfigSpace.configuration_space
  File "ConfigSpace/hyperparameters.pyx", line 1, in init ConfigSpace.hyperparameters
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**To Reproduce**
First I created a fresh conda environment to install deephyper:
conda create -n deephyper-Feb21 python=3.7
conda activate deephyper-Feb21
git clone https://github.com/deephyper/deephyper.git
cd deephyper/
pip install -e .

Then I ran this example from the deephyper documentation:
deephyper hps ambs --problem deephyper.benchmark.hps.polynome2.Problem --run deephyper.benchmark.hps.polynome2.run
(from this page: https://deephyper.readthedocs.io/en/latest/run/local.html) 

**Desktop (please complete the following information):**
 - OS: macOS Mojave 
 - System: laptop
 - Python version 3.7.10
 - DeepHyper version: installation from Github on Feb 23, 2021: git+https://github.com/deephyper/deephyper.git@571448aeb24c4d07ed4e864bd818c4847d70c93b#egg=deephyper
 - NumPy version: 1.18.5

**Comment by BethanyL** [comment]
I changed the title to be more general because I was able to reproduce the bug without using an HPO search example. I started over with the conda environment and just ran "deephyper --help". This resulted in the same error:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/deephyper-Feb23-21/bin/deephyper", line 33, in <module>
    sys.exit(load_entry_point('deephyper', 'console_scripts', 'deephyper')())
  File "/opt/anaconda3/envs/deephyper-Feb23-21/bin/deephyper", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/anaconda3/envs/deephyper-Feb23-21/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 98, in load
    module = import_module(match.group('module'))
  File "/opt/anaconda3/envs/deephyper-Feb23-21/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/blusch/deephyper/deephyper/core/cli/__init__.py", line 1, in <module>
    from deephyper.core.cli.cli import main
  File "/Users/blusch/deephyper/deephyper/core/cli/cli.py", line 9, in <module>
    from deephyper.core.cli import hps, nas, balsam_submit
  File "/Users/blusch/deephyper/deephyper/core/cli/hps.py", line 6, in <module>
    from deephyper.search.util import load_attr_from
  File "/Users/blusch/deephyper/deephyper/search/__init__.py", line 6, in <module>
    from deephyper.search.search import Search
  File "/Users/blusch/deephyper/deephyper/search/search.py", line 8, in <module>
    from deephyper.evaluator.evaluate import Evaluator
  File "/Users/blusch/deephyper/deephyper/evaluator/__init__.py", line 5, in <module>
    from deephyper.evaluator.evaluate import Encoder
  File "/Users/blusch/deephyper/deephyper/evaluator/evaluate.py", line 14, in <module>
    import skopt
  File "/opt/anaconda3/envs/deephyper-Feb23-21/lib/python3.7/site-packages/skopt/__init__.py", line 45, in <module>
    from . import callbacks
  File "/opt/anaconda3/envs/deephyper-Feb23-21/lib/python3.7/site-packages/skopt/callbacks.py", line 17, in <module>
    from skopt.utils import dump
  File "/opt/anaconda3/envs/deephyper-Feb23-21/lib/python3.7/site-packages/skopt/utils.py", line 19, in <module>
    from .sampler import Sobol, Lhs, Hammersly, Halton, Grid
  File "/opt/anaconda3/envs/deephyper-Feb23-21/lib/python3.7/site-packages/skopt/sampler/__init__.py", line 4, in <module>
    from .lhs import Lhs
  File "/opt/anaconda3/envs/deephyper-Feb23-21/lib/python3.7/site-packages/skopt/sampler/lhs.py", line 9, in <module>
    from ..space import Space, Categorical
  File "/opt/anaconda3/envs/deephyper-Feb23-21/lib/python3.7/site-packages/skopt/space/__init__.py", line 5, in <module>
    from .space import *
  File "/opt/anaconda3/envs/deephyper-Feb23-21/lib/python3.7/site-packages/skopt/space/space.py", line 27, in <module>
    import ConfigSpace as CS
  File "/opt/anaconda3/envs/deephyper-Feb23-21/lib/python3.7/site-packages/ConfigSpace/__init__.py", line 37, in <module>
    from ConfigSpace.configuration_space import Configuration, \
  File "ConfigSpace/configuration_space.pyx", line 39, in init ConfigSpace.configuration_space
  File "ConfigSpace/hyperparameters.pyx", line 1, in init ConfigSpace.hyperparameters
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by jke513** [comment]
can you try to install the following version of configspace?
`pip install ConfigSpace==0.4.14 `

**Comment by BethanyL** [comment]
When I installed deephyper, it installed ConfigSpace-0.4.16. I tried the above command to revert to 0.4.14, but I get this error:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
deephyper 0.2.1 requires ConfigSpace==0.4.16, but you have configspace 0.4.14 which is incompatible.

**Comment by Deathn0t** [comment]
Hello, yes this is a known bug not yet corrected in the master branch. It is apparently coming from the different 2.x versions of Tensorflow which have different restrictions for the Numpy version. The follow set of dependencies that you can edit in the `setup.py` should work. However, you should create a new fresh conda environment to make sure it does.

```
REQUIRED = [
    "tensorflow>=2.0.0",
    "numpy",  # working with 1.20.1
    "dh-scikit-optimize==0.8.3",
    "scikit-learn>=0.23.1",
    "tqdm",
    "keras",
    "deap",  # GA search
    # nas
    "gym",
    "networkx",
    "joblib>=0.10.3",
    "pydot",
    "ray>=0.7.6",
    "pandas>=0.24.2",
    "Jinja2",
    "ConfigSpace==0.4.17",
    "xgboost",
    "typeguard",
    "openml==0.10.2",
    "matplotlib>=3.0.3",
]
```

Let me know if this solves your issue.

**Comment by Deathn0t** [comment]
The versions where updated in d110b778c0794e4276511e7e53920075b0e84c3e to avoid this issue.
However, it is good to run `pip install --upgrade pip` to make sure that the latest build policy is for wheels (used by ConfigSpace) is available.
