### ISSUE TITLE
[BUG] Post-training pipeline raise: KeyError: 'post_train'

### ISSUE THREAD

**Issue by Deathn0t** [deephyper/deephyper#57]
Encountered by @Romit-Maulik.

Edit by @Romit-Maulik  to fill in details.

**Describe the bug**

```
Uncaught exception <class 'KeyError'>: 'post_train'Traceback (most recent call last):
  File "/lus/theta-fs0/projects/datascience/rmaulik/AE_Search/deephyper_repo/deephyper/evaluator/runner.py", line 36, in <module>
    retval = func(d)
  File "/lus/theta-fs0/projects/datascience/rmaulik/AE_Search/deephyper_repo/deephyper/post/pipeline.py", line 47, in train
    repeat = config["post_train"]["repeat"]
KeyError: 'post_train'
```

**To Reproduce**
After a successful deployment of NAS - I followed the steps in the NAS post-training documentation [here](https://deephyper.readthedocs.io/en/latest/search/nas/nas.html#post-training). Briefly, these are:
1. Create a new app for post-training
```
balsam app --name POST --exe "$(which python) -m deephyper.post.train"
```
2. Find the best architectures from within a Balsam database.
```
deephyper-analytics json best -n 100 -p /home/rmaulik/project_link/AE_Search/swe_ae_search_db/data/swe_ensemble_0/swe_ensemble_0_0022b977/swe_ensemble_0_2021-03-06_21.json
```
3. Create and submit a post-training job
```
balsam job --name post_ensemble_0 --workflow post_ensemble_0 --app POST --args '--evaluator balsam --problem swe_ae_search.swe_ensemble_0.problem.Problem --fbest /home/rmaulik/project_link/AE_Search/swe_ae_search_db/data/swe_ensemble_0/swe_ensemble_0_0022b977/best_archs.json'
```
and 
```
balsam submit-launch -n 8 -q debug-cache-quad -t 60 -A datascience --job-mode mpi --wf-filter post_ensemble_0
```

**Expected behavior**
A post-training run of the best-architectures and their metrics in `/home/rmaulik/project_link/AE_Search/swe_ae_search_db/data/post_ensemble_0`. In addition, it would be desirable to save the trained models as *.h5 files in the different task subdirectories.

**System**
This was performed on Theta KNL.

**Comment by Deathn0t** [comment]
In fact the problem needs to define the `post_training` config such as:

```python
Problem.post_training(
        num_epochs=1000,
        metrics=['r2'],
        callbacks=dict(
        ModelCheckpoint={
            'monitor': 'val_r2',
            'mode': 'max',
            'save_best_only': True,
            'verbose': 1
        },
        EarlyStopping={
            'monitor': 'val_r2',
            'mode': 'max',
            'verbose': 1,
            'patience': 10
        },
        TensorBoard={
            'log_dir':'tb_logs',
            'histogram_freq':1,
            'batch_size':64,
            'write_graph':True,
            'write_grads':True,
            'write_images':True,
            'update_freq':'epoch'
        })
)
```

I also added a more informative error in case someone forgets about it, see 08586e9879b17d6ed7b9dd942e3aa4b5edd4c140.
