### ISSUE TITLE
[BUG] DeepHyper Installation on Cooley

### ISSUE THREAD

**Issue by tanwimallick** [deephyper/deephyper#60]
**Describe the bug**
Installed DeepHyper from source on Cooley as described in the documentation. Got the error as follows  

```
from deephyper.benchmark.datasets import airlines as dataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lus/theta-fs0/projects/hpcbdsm/deephyper/deephyper/benchmark/__init__.py", line 5, in <module>
    from deephyper.benchmark.problem import HpProblem, NaProblem
  File "/lus/theta-fs0/projects/hpcbdsm/deephyper/deephyper/benchmark/problem.py", line 1, in <module>
    from deephyper.problem import HpProblem
  File "/lus/theta-fs0/projects/hpcbdsm/deephyper/deephyper/problem/__init__.py", line 1, in <module>
    import ConfigSpace as config_space
ImportError: No module named 'ConfigSpace'
```

** System information:**
 - System: Cooley
 - Python version: 3.7
 - DeepHyper Version: 0.0.7

**Comment by Deathn0t** [comment]
This set of installation instructions resolved the issue, however the user has to be careful if sometimes a specific Tensorflow version has to be used.

```bash
conda update conda -y
conda create -p dhtest python=3.7
soft add +cuda-10.2
conda install gxx_linux-64 gcc_linux-64 -y
pip install deephyper
```
