### ISSUE TITLE
could not install the deephyper.

### ISSUE THREAD

**Issue by ml-rakesh** [deephyper/deephyper#65]
I am installing deephyper using, `pip install deephper`, but i am getting error:
 ```
 Running setup.py clean for yarl
  Building wheel for multidict (PEP 517) ... error
  Complete output from command /usr/bin/python3 /usr/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp0rmzbrl6:
  *********************
  * Accelerated build *
  *********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/multidict
  copying multidict/_compat.py -> build/lib.linux-x86_64-3.6/multidict
  copying multidict/__init__.py -> build/lib.linux-x86_64-3.6/multidict
  copying multidict/_multidict_py.py -> build/lib.linux-x86_64-3.6/multidict
  copying multidict/_abc.py -> build/lib.linux-x86_64-3.6/multidict
  copying multidict/_multidict_base.py -> build/lib.linux-x86_64-3.6/multidict
  running egg_info
  writing multidict.egg-info/PKG-INFO
  writing dependency_links to multidict.egg-info/dependency_links.txt
  writing top-level names to multidict.egg-info/top_level.txt
  adding license file 'LICENSE' (matched pattern 'LICENSE')
  reading manifest file 'multidict.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files found matching 'multidict/_multidict.html'
  warning: no previously-included files found matching 'multidict/*.so'
  warning: no previously-included files found matching 'multidict/*.pyd'
  warning: no previously-included files found matching 'multidict/*.pyd'
  no previously-included directories found matching 'docs/_build'
  writing manifest file 'multidict.egg-info/SOURCES.txt'
  copying multidict/__init__.pyi -> build/lib.linux-x86_64-3.6/multidict
  copying multidict/_multidict.c -> build/lib.linux-x86_64-3.6/multidict
  copying multidict/py.typed -> build/lib.linux-x86_64-3.6/multidict
  creating build/lib.linux-x86_64-3.6/multidict/_multilib
  copying multidict/_multilib/defs.h -> build/lib.linux-x86_64-3.6/multidict/_multilib
  copying multidict/_multilib/dict.h -> build/lib.linux-x86_64-3.6/multidict/_multilib
  copying multidict/_multilib/istr.h -> build/lib.linux-x86_64-3.6/multidict/_multilib
  copying multidict/_multilib/iter.h -> build/lib.linux-x86_64-3.6/multidict/_multilib
  copying multidict/_multilib/pair_list.h -> build/lib.linux-x86_64-3.6/multidict/_multilib
  copying multidict/_multilib/views.h -> build/lib.linux-x86_64-3.6/multidict/_multilib
  running build_ext
  building 'multidict._multidict' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/multidict
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c multidict/_multidict.c -o build/temp.linux-x86_64-3.6/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
  multidict/_multidict.c:1:20: fatal error: Python.h: No such file or directory
   #include "Python.h"
                      ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for multidict
  Running setup.py clean for multidict
Failed to build yarl multidict
Could not build wheels for yarl, multidict which use PEP 517 and cannot be installed directly
```

**Comment by Deathn0t** [comment]
Hello @ml-rakesh,

Could help me understand the issue by providing more details about what you are doing. For example, what is your python environment, where do you try to install the package, are you using a specific `setup.py`.

Also the full stack trace, including the command executed could help.

**Comment by ml-rakesh** [comment]
hello @Deathn0t 

I am using operating system:
           `Amazon Linux AMI release 2018.03`
python version:
          `python 3.6.13`.

I am trying to install deephyper using CLI:
         `sudo -H pip install deephyper`

below are the installation log file:

[pip_deephyper.zip](https://github.com/deephyper/deephyper/files/6317769/pip_deephyper.zip)

**Comment by Deathn0t** [comment]
Thank you @ml-rakesh 
so the issue with with the `ConfigSpace` dependency


```
2021-04-15T12:09:24 Could not build wheels for ConfigSpace, multidict, yarl which use PEP 517 and cannot be installed directly
2021-04-15T12:09:24 Exception information:
2021-04-15T12:09:24 Traceback (most recent call last):
2021-04-15T12:09:24   File "/usr/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 179, in main
2021-04-15T12:09:24     status = self.run(options, args)
2021-04-15T12:09:24   File "/usr/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 364, in run
2021-04-15T12:09:24     ", ".join(r.name for r in build_failures)))
2021-04-15T12:09:24 pip._internal.exceptions.InstallationError: Could not build wheels for ConfigSpace, multidict, yarl which use PEP 517 and cannot be installed directly
2021-04-15T12:09:24 You are using pip version 19.0.2, however version 21.0.1 is available.
2021-04-15T12:09:24 You should consider upgrading via the 'pip install --upgrade pip' command.
```

To resolve this issue on Linux you should install `build-essential` before installing deephyper with the following command:
```bash
sudo apt-get install build-essential
```

Tell me if it resolves the issue.

**Comment by ml-rakesh** [comment]
while installing build-essential, i am getting this:
```
sh-4.2$ sudo yum install build-essential
Loaded plugins: dkms-build-requires, priorities, update-motd, upgrade-helper, versionlock
amzn-main                                                                                                                                                  | 2.1 kB  00:00:00     
amzn-updates                                                                                                                                               | 3.8 kB  00:00:00     
No package build-essential available.
Error: Nothing to do
```
after this, i tried to install deephyper again,
```
ERROR: Could not find a version that satisfies the requirement deephyper (from versions: none)
ERROR: No matching distribution found for deephyper
```

**Comment by Deathn0t** [comment]
According to this post https://serverfault.com/questions/204893/aws-ec2-and-build-essential/460295
The equivalent with `yum` is:

```
yum install make glibc-devel gcc patch
```

**Comment by ml-rakesh** [comment]
the command yum:
`yum install make glibc-devel gcc patch`

showing this:
```
sh-4.2$ sudo yum install make glibc-devel gcc patch
Loaded plugins: dkms-build-requires, priorities, update-motd, upgrade-helper, versionlock
amzn-main                                                                                                                                                  | 2.1 kB  00:00:00     
amzn-updates                                                                                                                                               | 3.8 kB  00:00:00     
Package 1:make-3.82-21.10.amzn1.x86_64 already installed and latest version
Package glibc-devel-2.17-292.180.amzn1.x86_64 already installed and latest version
Package gcc-4.8.5-1.22.amzn1.noarch already installed and latest version
Package patch-2.7.1-12.14.amzn1.x86_64 already installed and latest version
Nothing to do
```

but still get the error:
```
ERROR: Could not find a version that satisfies the requirement deephyper (from versions: none)
ERROR: No matching distribution found for deephyper
```

**Comment by Deathn0t** [comment]
Okay so also try to do `pip install --upgrade pip` before installing deephyper.

**Comment by ml-rakesh** [comment]
yeah, I did this but still get the same error.

**Comment by Deathn0t** [comment]
Could you please send again the latest log file from the installation?

**Comment by ml-rakesh** [comment]
yeah, below are the log file of deephyper installation:

```
sh-4.2$ sudo -H pip install deephyper
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
ERROR: Could not find a version that satisfies the requirement deephyper (from versions: none)
ERROR: No matching distribution found for deephyper
```

**Comment by Deathn0t** [comment]
So it looks like you are doing different things. In the first log file you shared me you where using Python 3.6.8, here for pip you are using Python 2.7. Make sure that you are using the good environment, it is likely that your issue is coming from there.

**Comment by ml-rakesh** [comment]
thanks, below error solved:
```
sh-4.2$ sudo -H pip install deephyper
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
ERROR: Could not find a version that satisfies the requirement deephyper (from versions: none)
ERROR: No matching distribution found for deephyper
```

but while installing i am getting same error:

[Uploading pip_deep.zip…]()

**Comment by Deathn0t** [comment]
It is still the same error, nothing was solved. To use the good pip probably use `pip3` instead of `pip`

**Comment by ml-rakesh** [comment]
yeah i used pip3 this time. but get the above same error.

**Comment by Deathn0t** [comment]
The error is still showing that you are using python 2.7 and Deephyper is not compatible with this version of Python.

**Comment by ml-rakesh** [comment]
no i think i am using `pip3`:
`sudo -H pip3 install deephyper`

where u see i am using `python2.7`?

**Comment by Deathn0t** [comment]
In the previous error messages you sent.

So you have to do
```
pip3 install pip --upgrade
pip3 install deephyper
```

**Comment by ml-rakesh** [comment]
thanks @Deathn0t 

it is working now

**Comment by Deathn0t** [comment]
Great, therefore I will close this thread.
