### ISSUE TITLE
[Doc] Tutorial 04 - NAS (Basic)

### ISSUE THREAD

**Issue by Deathn0t** [deephyper/deephyper#92]
- [ ] load the data
- [ ] search space with factory
- [ ] problem instance
- [ ] run locally
- [ ] run on Theta
- [ ] run on ThetaGPU
- [ ] analyse the results

**Comment by krm9c** [comment]
This tutorial required setup of graphviz and pydot which gave me some errors. Maybe add this dependency to the tutorial in the text.

**Comment by krm9c** [comment]
outpout to output under the plot of epoch

**Comment by jke513** [comment]
I also found the same errors regarding graphviz and pydot. 

(deephyper) ➜  polynome2 (develop) ✗ python search_space.py
2021-08-08 20:19:53.421806: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
The output tensor of shape (2,) doesn't match the expected shape (1,)!
Traceback (most recent call last):
  File "search_space.py", line 116, in <module>
    factory.plot_model(**shapes)
  File "/Users/jkoo/opt/anaconda3/envs/deephyper/lib/python3.8/site-packages/typeguard/__init__.py", line 927, in wrapper
    retval = func(*args, **kwargs)
  File "/Users/jkoo/research/github/deephyper/deephyper/nas/space/factory.py", line 69, in plot_model
    plot_model(model, to_file=fname, show_shapes=show_shapes)
  File "/Users/jkoo/opt/anaconda3/envs/deephyper/lib/python3.8/site-packages/tensorflow/python/keras/utils/vis_utils.py", line 322, in plot_model
    dot = model_to_dot(
  File "/Users/jkoo/opt/anaconda3/envs/deephyper/lib/python3.8/site-packages/tensorflow/python/keras/utils/vis_utils.py", line 114, in model_to_dot
    raise ImportError(message)
ImportError: ('You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) ', 'for plot_model/model_to_dot to work.')

**Comment by Deathn0t** [comment]
I added this comment at the beginning of the tutorial:
<img width="730" alt="Screenshot 2021-08-10 at 09 15 34" src="https://user-images.githubusercontent.com/5201978/128824414-469d398f-2ef3-428e-8f32-f92747ec4cf5.png">

@krm9c what do you mean by :
> outpout to output under the plot of epoch

**Comment by krm9c** [comment]
@Deathn0t  There was a typo in the tutorial, where you say outpout, which should be output. It was just under the plot pf val_r2 vs epoch
