### ISSUE TITLE
[Doc] Tutorial 01 - HPS for ML (Basic)

### ISSUE THREAD

**Issue by Deathn0t** [deephyper/deephyper#95]

**Comment by krm9c** [comment]
When I created a problem with rf_tuning, there were existing load_Data, problem and model_run in the folder. However, these files include a NN example instead of an random forest example. I first ran the NN example and then replaced all these functions with Random forest example. I was able to execute both. Maybe, create a blank directory instead of nn example when defining a problem.


Also, in the final step where I look for the best config. 

I received this error and could not find a test_config file

Traceback (most recent call last):
  File "test_best_config.py", line 2, in <module>
    from test_config import test_config
ModuleNotFoundError: No module named 'test_config'


Was I supposed to create a test_config file somewhere, if so, I could not find the details in the tutorial.

**Comment by jke513** [comment]
I also have the same issue. 

(deephyper) ➜  rf_tuning (develop) ✗ python test_best_config.py 
Traceback (most recent call last):
  File "test_best_config.py", line 2, in <module>
    from test_config import test_config
ModuleNotFoundError: No module named 'test_config'

**Comment by Deathn0t** [comment]
I resolved this issue here https://github.com/deephyper/tutorials/commit/7c147e9fda6bb308333c689390c3d36c4dbf8eb4
